Fix workflow

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -1,7 +1,7 @@
 name: ansible_test
 on:
   push:
-    brances:
+    branches:
       - master
   pull_request:
     branches:
@@ -20,3 +20,8 @@ jobs:
         run: ansible-playbook -v ./dev-brew-provisioning.yml --syntax-check
       - name: Runnning Playbook
         run: ansible-playbook -v ./dev-brew-provisioning.yml
+      - name: Idempotence Test
+        run: |
+          ansible-playbook -v dev-brew-provisioning.yml | grep -q 'changed=0.*failed=0'
+          && (echo 'Idempotence test: pass' && exit 0)
+          || (echo 'Idempotence test: fail' && exit 1)
